###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "zoro",
    "name": "zoro",
    "password": "zoro@123"
}

###
GET http://localhost:3003/api/users

###
DELETE http://localhost:3003/api/blogs/6a70b98ddb1717b6060c36cc
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "143 laa laa laa",
  "author": "zoro",
  "url": "examples.com",
  "userId": "6a70823595cf6369d703e5c0"
}