GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "laa laa laa",
  "author": "zoro",
  "url": "examples.com"
}

###
DELETE  http://localhost:3003/api/blogs/6a67f483f037ba3d40c0c0a5